# Generated by Django 6.0.6 on 2026-06-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('color', 'color'), ('size', 'size')], default='size', max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('price_modifier', models.FloatField(default=0.0, help_text='Additional price for this variation (optional)')),
                ('active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.item')),
            ],
        ),
    ]
