# Generated by Django 6.0.6 on 2026-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='currency_symbol',
            field=models.CharField(default='৳', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_about_text',
            field=models.TextField(blank=True, help_text='About text in footer description', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_copyright_text',
            field=models.CharField(default='© 2026 Django E-commerce. All rights reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='free_shipping_threshold',
            field=models.FloatField(default=2000.0, help_text='Free shipping on orders above this amount'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics G-XXXXXX ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_title',
            field=models.CharField(default='Best E-commerce Store', help_text='SEO Title', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='promo_banner_text',
            field=models.CharField(blank=True, default='Special Discount! Use code WELCOME10 for 10% off.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_promo_banner',
            field=models.BooleanField(default=True, help_text='Show promo bar at the top of site'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_favicon',
            field=models.ImageField(blank=True, help_text='Upload website favicon', null=True, upload_to='site_config/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Upload website logo', null=True, upload_to='site_config/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tax_rate_percentage',
            field=models.FloatField(default=0.0, help_text='Tax rate in percentage'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Enable to put site in Maintenance Mode'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='shipping_cost',
            field=models.FloatField(default=60.0, help_text='Default shipping fee'),
        ),
    ]
