# Generated by Django 6.0.6 on 2026-06-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_siteconfiguration_currency_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='Custom meta description. Defaults to product short description if blank.', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='seo_meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='seo_meta_title',
            field=models.CharField(blank=True, help_text='Custom meta title. Defaults to product title if blank.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='seo_og_description',
            field=models.TextField(blank=True, help_text='Social media sharing (Open Graph) description.', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='seo_og_image',
            field=models.ImageField(blank=True, help_text='Social media sharing (Open Graph) image. Defaults to main product image if blank.', null=True, upload_to='og_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='seo_og_title',
            field=models.CharField(blank=True, help_text='Social media sharing (Open Graph) title.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='seo_schema_markup',
            field=models.TextField(blank=True, help_text='JSON-LD schema markup for structured search snippets.', null=True),
        ),
    ]
