# Generated by Django 6.0.6 on 2026-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_item_seo_meta_description_item_seo_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook_page_access_token',
            field=models.TextField(blank=True, help_text='Page Access Token for Facebook Messenger API', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook_verify_token',
            field=models.CharField(default='my_verify_token_123', help_text='Verification token for Facebook Webhook connection', max_length=255),
        ),
    ]
