# Generated by Django 6.0.6 on 2026-06-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_siteconfiguration_facebook_page_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='facebook_page_access_token',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='facebook_verify_token',
        ),
    ]
