# Generated by Django 6.0.6 on 2026-06-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_siteconfiguration_facebook_page_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('secondary_banner', 'Secondary Top Banner (Stack of 2 next to Hero)'), ('model_banner', 'Model Banner (Grid under Hero)'), ('gadget_feature', 'Gadget Feature Banner (Grid of 3)'), ('promo_block', 'Promo Block Banner (Grid of 2)'), ('special_banner', 'Special Banner (Widescreen bottom grid)')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, help_text='Small tagline or badge text', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Description or subtitle', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome icon class (e.g. fas fa-credit-card)', max_length=100, null=True)),
                ('link_url', models.CharField(default='/shop/', help_text='Target URL or link', max_length=255)),
                ('background_style', models.CharField(blank=True, help_text='CSS background style (e.g. linear-gradient(135deg, #1e1b4b, #312e81))', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
                'ordering': ['order', 'id'],
            },
        ),
    ]
