# Generated by Django 6.0.6 on 2026-06-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_promobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Image alt tag for search engine indexing and accessibility.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='Custom meta description. Defaults to category description if blank.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_meta_title',
            field=models.CharField(blank=True, help_text='Custom meta title. Defaults to category title if blank.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Image alt tag for search engine indexing and accessibility.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='link_title',
            field=models.CharField(blank=True, help_text='Link title attribute for search engines.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='seo_rel_attribute',
            field=models.CharField(blank=True, default='noopener noreferrer', help_text="Link rel attribute (e.g. 'nofollow', 'noopener noreferrer').", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Image alt tag for search engine indexing and accessibility.', max_length=150, null=True),
        ),
    ]
