# Generated by Django 6.0.6 on 2026-06-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_image_alt_category_seo_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('file', models.FileField(blank=True, help_text='Upload product image or video file (MP4 format).', null=True, upload_to='product_media/')),
                ('video_url', models.URLField(blank=True, help_text='Or paste external video link (e.g. YouTube/Vimeo).', null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image (strongly recommended for video files).', null=True, upload_to='product_media/thumbnails/')),
                ('image_alt', models.CharField(blank=True, help_text='SEO alt text for accessibility and search indexing.', max_length=150, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='products.item')),
            ],
            options={
                'verbose_name': 'Product Media',
                'verbose_name_plural': 'Product Gallery Media',
                'ordering': ['order', 'id'],
            },
        ),
    ]
