# Generated by Django 6.0.6 on 2026-06-22 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_user'),
        ('products', '0008_siteconfiguration_facebook_page_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(help_text='Page-Scoped ID of the user', max_length=100, unique=True)),
                ('state', models.CharField(default='IDLE', help_text='Current session conversational state', max_length=50)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of item to purchase')),
                ('phone_number', models.CharField(blank=True, help_text='Customer phone number', max_length=20, null=True)),
                ('shipping_address', models.TextField(blank=True, help_text='Customer shipping address', null=True)),
                ('district', models.CharField(blank=True, default='Facebook Bot', help_text='District for shipping', max_length=100, null=True)),
                ('selected_item', models.ForeignKey(blank=True, help_text='Selected product item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.item')),
            ],
        ),
    ]
