# Generated by Django 6.0.6 on 2026-06-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_facebooksession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookSession',
        ),
    ]
