# Generated by Django 6.0.6 on 2026-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_orderitem_user'),
        ('products', '0007_item_seo_meta_description_item_seo_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='products.variation'),
        ),
    ]
